cache:
- "c:\\sr -> appveyor.yml" # stack root, short paths == less problems

build: off

before_test:
- curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
- 7z x stack.zip stack.exe

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
- stack setup > nul
- stack ghc -- --version
- echo "" | stack --no-terminal build
- stack exec java-poker-helloworld
- ps: Write-Host $PWD
- ps: Get-ChildItem
- ps: ./stack.exe exec java-poker-helloworld
- ps: & ./stack.exe exec java-poker-helloworld
- ps: ./stack.exe exec java-poker
- ps: Write-Host "123`ny`nn`n" | ,/stack exec java-poker
